on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Setup Env
        run |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name Run Test
        run: make test/all
