on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        uses: abatilo/actions/poetry@v1.0.0
        with:
          python_version: 3.7.0
          poetry_version: 1.5.0
          args: install
      - name: Run test
        uses: abatilo/actions/poetry@v1.0.0
        with:
          python_version: 3.7.0
          poetry_version: 1.5.0
          args: run pytest tests
